Cameras
StalkerSanya/MY-Robot pull request #1
Opened 2019-11-11 19:18 UTC by StalkerSanya

Adding many features: control, scripts, camera and maybe something else, I already don't remember.

2019-11-12 12:44 UTC, l1va requested changes

2019-11-12 12:44 UTC, l1va commented on controller/CMakeLists.txt
> +## Find catkin macros and libraries
do you really need all these comments?

2019-11-12 12:44 UTC, l1va commented on my_robot_gazebo/urdf/my_robot.urdf.xacro
> +  <gazebo reference="camera_link">
might be better to put a camera in a separate of model file ?

2019-11-12 12:44 UTC, l1va commented on scripts/CMakeLists.txt
> +# add_compile_options(-std=c++11)
have you seen some where cmakelists inside scripts folder? If you use scripts as package - bad package name then.

2019-11-12 12:44 UTC, l1va commented on scripts/camerascript.py
> +    		filename = '/home/sanekcd/my_robot_ws/src/project1/screens_robot/camera_image' + str(j) + '.png'
hardcode that will not work on my laptop

2019-11-14 19:57 UTC, merged

2019-11-15 09:03 UTC, StalkerSanya commented on controller/CMakeLists.txt
> +## Find catkin macros and libraries
fixed

2019-11-15 09:03 UTC, StalkerSanya commented on my_robot_gazebo/urdf/my_robot.urdf.xacro
> +  <gazebo reference="camera_link">
fixed

2019-11-15 09:04 UTC, StalkerSanya commented on scripts/CMakeLists.txt
> +# add_compile_options(-std=c++11)
fixed

2019-11-15 09:07 UTC, StalkerSanya commented on scripts/camerascript.py
> +    		filename = '/home/sanekcd/my_robot_ws/src/project1/screens_robot/camera_image' + str(j) + '.png'
fixed, but with filepath "~/Pictures/camera_image + str(j) + .png" it doesn't save images in end folder. I don't know why