tests
StalkerSanya/MY-Robot pull request #4
Opened 2019-11-16 11:09 UTC by StalkerSanya

added new package with unit test and integration test

2019-11-22 15:25 UTC, l1va requested changes

2019-11-22 15:25 UTC, l1va commented on my_robot_gazebo/launch/xacro.launch
> +										joint8_position_controller"/> -->
why do you hide it?

2019-11-22 15:25 UTC, l1va commented on tests/integration_test/scripts/sub.py
> +	if abs(msg.set_point-msg.process_value) < 0.01:
where are asserts?

2019-11-22 15:25 UTC, l1va commented on tests/integration_test/scripts/sub.py
> +	wheel1_topic = '/crobot/joint5_position_controller/state'
copied Ramil's code.

2019-11-22 15:25 UTC, l1va commented on tests/unit_test/unit.py
> +		self.assertEqual(np.sum((FK(20*3.142/180)- b) < 0.001), 3)
it is dangerous to test on sum but the interesting idea)

2019-11-24 20:24 UTC, StalkerSanya commented on my_robot_gazebo/launch/xacro.launch
> +										joint8_position_controller"/> -->
I checked something, but I have not remembered what already. In new comment "fixed" I  revealed

2019-11-24 20:25 UTC, StalkerSanya commented on tests/integration_test/scripts/sub.py
> +	if abs(msg.set_point-msg.process_value) < 0.01:
Added asserts in new commit "fixed"

2019-11-24 20:27 UTC, StalkerSanya commented on tests/integration_test/scripts/sub.py
> +	wheel1_topic = '/crobot/joint5_position_controller/state'
Thanks for observation. Already fixed in new commit "fixed"

2019-11-24 20:28 UTC, StalkerSanya commented on tests/unit_test/unit.py
> +		self.assertEqual(np.sum((FK(20*3.142/180)- b) < 0.001), 3)
It is dangerous, but it works (until)

2019-11-25 13:11 UTC, l1va approved these changes

2019-11-26 08:56 UTC, merged